### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by elisementor** [redstardeveloper/Colmar-Academy#6]
Grade: Exceeds Expectations

Great job!

It is a joy to review this beautiful project. You did a fantastic job and your code is clear and well organized. Your folder structure is great, and you used a reset.css. Your mobile version is perfect and your desktop version could use only minor tweaks. Kudos!
 
Areas for improvement are minor. Add a favicon in your head. This will make the browser tab identify the page. To reduce css repetition, experiment with a few more universal classes, like media containers, but also classes for left and right in the two-column panels. Panels 1, 2, and 4 all have the same ratio of left to right (60-40) so you can make universal classes accordingly. Some padding adjustment might be necessary. 
 
As extra challenges, you could make more design choices. You perfectly recreated the wireframes. Now change the colors and buttons. Also build out some more pages of the site using images you find on royalty free image sites like unsplash and pixabay. 
 
Great job!

**Comment by pablospaniard** [comment]
Thank you!
